# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'client_end' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for client_end

  target 'client_end-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'client_end-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for client_end-tvOS

end
